# General settings for termination
termination:
  word: "APPROVE"
  max_message_turns: 13
  max_turns: 3

# LLM configuration
llm_config:
  provider: "openai"
  model_name: "gpt-4o-mini"
  max_tokens: 8192

# Agent configurations
agents:
  # Inner Team Agents
  - name: "PlannerAgent"
    system_message_key: "PlannerAgent" 
    is_user_proxy: false

  - name: "RecipeAgent"
    system_message_key: "RecipeAgent"
    is_user_proxy: false

  - name: "CritiqueAgent"
    system_message_key: "CritiqueAgent"
    is_user_proxy: false

  # Inner Team User Proxy Agent
  - name: "CulinaryTeamUserApproval"
    system_message_key: "CulinaryTeamUserApproval"
    is_user_proxy: true
    human_input_mode: "ALWAYS" 

  # Outer Team Agents
  - name: "CulinaryTeamAgent"
    system_message_key: "CulinaryTeamAgent"
    is_user_proxy: false

  - name: "LogisticAgent"
    system_message_key: "LogisticAgent"
    is_user_proxy: false

  - name: "BudgetAgent"
    system_message_key: "BudgetAgent"
    is_user_proxy: false

  # Outer Team User Proxy Agent
  - name: "FinalApproval"
    system_message_key: "FinalApproval"
    is_user_proxy: true
    human_input_mode: "ALWAYS"